<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-4352</name>
   <tag></tag>
   <elementGuidId>7620edec-a22c-4305-bd52-bf33efbd11ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4352</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4352']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16b4f13e-944d-4ea7-8ed7-4278a08cef79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4352</value>
      <webElementGuid>fd83b3d6-f212-4261-8b1d-9fb32dcb75f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>887d6d3d-690d-420e-86f8-22297fe41de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4352&quot;)</value>
      <webElementGuid>c5f83358-1cfa-4dc1-9009-533172572fde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4352']</value>
      <webElementGuid>1d083ab9-322c-4d4b-bd15-c3572fc595f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>f9a8c1d9-de1a-4493-8fef-98336def9084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9db246d1-e7e0-47c2-bf67-3edabff88c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4352' and @type = 'text']</value>
      <webElementGuid>7f9da474-0c74-4362-a086-f5ed0e4fd39b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
