<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-4388</name>
   <tag></tag>
   <elementGuidId>dc99c50d-94e8-4db5-8651-fce77e9fa985</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4388</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4388']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3745853-1d0f-4fbc-8182-85e8d7dadeae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4388</value>
      <webElementGuid>12e59a9e-9742-4bc8-88bb-9d9b9fa869c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dbc0f092-7ede-4074-a12f-76b46bad7579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4388&quot;)</value>
      <webElementGuid>0f391046-3641-4c60-8c3d-0c8365a88592</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4388']</value>
      <webElementGuid>8d1dbf6a-b79b-4dfe-b1d2-9a18809fd74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>a183a1e0-38a0-4d4a-b62c-165145ab29ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>eef7dd35-4dbf-4d8a-a6a6-93e8b5974a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4388' and @type = 'text']</value>
      <webElementGuid>db3fcb79-c99c-4cf7-91a2-e3d52a94b68d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
