<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-4391</name>
   <tag></tag>
   <elementGuidId>bd92c095-51c5-48dc-a36e-f2d9191c7925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4391</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4391']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>758eb779-5b89-4500-a7d2-40c17bed5393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4391</value>
      <webElementGuid>1d7c93a8-b169-400b-a6f0-051a95d2c0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c5b2a88-cbc2-4457-b16f-5c43b16aee6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4391&quot;)</value>
      <webElementGuid>95ee061a-55c6-44bb-88d0-f503e438bcb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4391']</value>
      <webElementGuid>4477607e-8b74-4676-881a-50b4c0474ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>058985bb-3f56-40b1-98c2-bb875814dba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>492c1948-33f3-4451-a3fe-dc8609de6dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4391' and @type = 'text']</value>
      <webElementGuid>3acb36e2-4c5f-4d7a-97fb-5f45647de653</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
