<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-4385</name>
   <tag></tag>
   <elementGuidId>194a5682-18d0-4285-b812-04a0bbf081bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4385</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4385']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65a4c160-3dda-454a-a841-dc21369a54ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4385</value>
      <webElementGuid>8b80166a-dcd8-4c3c-ae9c-feee4306ce38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ecf91fe-aeac-4786-a3d2-e5554d0e6cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4385&quot;)</value>
      <webElementGuid>5df8e7ba-9bee-4cf9-aae0-5281c964d3f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4385']</value>
      <webElementGuid>7b8acbc3-c6af-4b9f-bc84-28c9ded9826b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>10650f8c-5c1f-4f7b-87df-fff205a77b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>41afdaf9-b7d3-4f3f-ae7a-5f99359addb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4385' and @type = 'text']</value>
      <webElementGuid>91c901fd-3592-4030-ab33-dac42f846e83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
