<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-4394</name>
   <tag></tag>
   <elementGuidId>bf43ec1c-5997-4101-8a8d-8b4b9f404ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4394</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4394']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fa07ecd-e909-4bb5-b760-925485ab1737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4394</value>
      <webElementGuid>5bd5e38a-6d6b-4332-9e1e-ead30b74373c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70f40cd8-51af-4db4-97dc-b5f50b4b8f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4394&quot;)</value>
      <webElementGuid>77096138-2703-47a1-a825-440a1119996e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4394']</value>
      <webElementGuid>26c65975-952f-4e2e-a059-b8ec6f8997d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>bf260d84-902b-4c8e-a5e0-6149fc8be9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>38c1f07b-916e-404b-a6c8-7a36cbd10617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4394' and @type = 'text']</value>
      <webElementGuid>f8de4710-52a3-4cd4-bfcc-6633b4bcf1a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
