<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-4361</name>
   <tag></tag>
   <elementGuidId>170820b8-dd17-4d44-baa5-c8456bbbf54e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4361</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4361']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf784432-8ce7-4fee-9ee3-cb88325a29d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4361</value>
      <webElementGuid>96f0bce1-53e5-4b99-ab28-97abbe313403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a5cacca-2ec1-494f-a49a-fd78a455021a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4361&quot;)</value>
      <webElementGuid>f7460c06-b5a0-4318-a2fa-5d5857cc984c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4361']</value>
      <webElementGuid>b68ae214-ce2d-4800-8ee8-e33e6df40b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>191c7bd4-ed4f-4b09-8cfd-1829b0f3d6a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>5f07b74d-345d-47de-a1d3-dec4bd1bfd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4361' and @type = 'text']</value>
      <webElementGuid>44660766-08f4-44c7-9e89-964ac179b1f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
