<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-4358</name>
   <tag></tag>
   <elementGuidId>da68b824-c9ce-4507-a5c5-126cf988f886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4358</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4358']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8562f6f-0dfb-479c-9257-128f1d89f981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4358</value>
      <webElementGuid>e590412c-ca2a-4bee-a019-b422c04b02ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10ea689a-1c7f-416b-8db8-ca27b30b16a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4358&quot;)</value>
      <webElementGuid>10b90eb0-a741-4953-97e8-a43b1c4e66c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4358']</value>
      <webElementGuid>ca427976-ccdc-4d73-80d9-a7191187ec1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>c9dbe8a3-a1c6-47c4-a73f-8bd6222c7c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3e83118d-0fdb-4044-a584-178d9b57d563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4358' and @type = 'text']</value>
      <webElementGuid>66211070-84e4-44f8-a438-8c8110615439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
