<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-4370</name>
   <tag></tag>
   <elementGuidId>1f8e0321-bfbe-4b9e-8b6e-b143c8c7ae1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4370</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4370']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99f84ce6-9a18-4e4f-8f0a-11e0c8960370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4370</value>
      <webElementGuid>2325adda-7ca9-40c1-bf7e-9cb78ce03699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c009e48-83cb-471a-8947-c5d652f3aafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4370&quot;)</value>
      <webElementGuid>66043be6-c43a-4937-b8a4-2b432ab8aaec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4370']</value>
      <webElementGuid>5cc5e4e4-b193-4637-b54f-6182e953487d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>855a4877-300c-4775-a7b9-957bc5c318b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8e65a76d-e42b-466a-b298-af3b6bc99180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4370' and @type = 'text']</value>
      <webElementGuid>fdb00fdb-527f-44a2-ba4f-9379d2b27b1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
