<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-4373</name>
   <tag></tag>
   <elementGuidId>5f8d2289-9652-4920-b6b7-56e52d35038a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4373</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4373']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2073a14f-3bf1-44b4-a808-5c4e587bd67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4373</value>
      <webElementGuid>d07c9788-8878-4433-96d0-4fae60be2504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bdf24958-8a41-45e9-9e3f-7d98d6de1a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4373&quot;)</value>
      <webElementGuid>4d445030-417b-4a05-9682-fb36211b8c34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4373']</value>
      <webElementGuid>a6e07c32-a8b9-4aaa-ac77-577501fbf220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>09b62cac-000b-4738-9151-43f916903664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>901f5975-8dc3-4ed3-955b-0ad410d0bf11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4373' and @type = 'text']</value>
      <webElementGuid>a9d15f62-2055-4cc6-af73-58b8fe6d8cb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
