<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-4319</name>
   <tag></tag>
   <elementGuidId>e57f55cf-7fa9-478e-9811-3a9016a5ce79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4319</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4319']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8c60774-5765-46c8-8e2f-1b1264629b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4319</value>
      <webElementGuid>156b441f-2682-4376-9630-1956dda70a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df662f8c-64fc-4455-85ec-8ca86d69af82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4319&quot;)</value>
      <webElementGuid>6946bf7b-57fe-4084-818d-7464a1a98f16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4319']</value>
      <webElementGuid>38df2694-69be-4a17-948d-e0a9fd30eafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>0b6b192e-4326-45ff-aa7b-94aa0b89c3a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>97c8c98f-75b7-43cf-999f-7839bb6b22f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4319' and @type = 'text']</value>
      <webElementGuid>08e184ce-b0a3-47f1-8694-c42be579db06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
