<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-4322</name>
   <tag></tag>
   <elementGuidId>3ccc9f7f-23b8-4ca5-a38f-fd3ffa68a38e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4322</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4322']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9f69ed3-93e2-4382-9964-8aaf4718df7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4322</value>
      <webElementGuid>96b95cde-b1f7-4e6e-8668-e5fc93ab9e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de075353-9f5a-4d18-829d-bae441e94586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4322&quot;)</value>
      <webElementGuid>2fb7c275-aa45-43ce-8b7e-e1e8fe240e12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4322']</value>
      <webElementGuid>b5800bea-59b9-416c-accd-43c06bff241e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>7acbe802-6781-4634-a0fe-a6b55c59b1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>1174d1ab-96c9-4662-90b3-97ca6c9df072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4322' and @type = 'text']</value>
      <webElementGuid>85cb01f0-523d-44bf-ae10-74a051bca3f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
