<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-4391</name>
   <tag></tag>
   <elementGuidId>0f01d133-5288-4067-a2f4-cb3e11524306</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4391</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4391']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53a27b50-b5e8-42e2-9c13-9ef0351c8b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4391</value>
      <webElementGuid>16e19695-6a10-4560-a0ea-b30eec94717d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e6893db8-5195-4248-a767-5603c39e0f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4391&quot;)</value>
      <webElementGuid>b515abd4-5ffc-4fe8-8931-acc511d6489e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4391']</value>
      <webElementGuid>7c2c4411-28ec-4e2a-870c-3312f7a5a303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>7447c160-745c-487e-9ca5-44b8768ebec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>e0464a76-9c52-417e-9286-d067daf8f950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4391' and @type = 'text']</value>
      <webElementGuid>702f6686-f5c6-47bf-bc10-3ca1fe07ec80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
