<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-4388</name>
   <tag></tag>
   <elementGuidId>28effe7c-0527-49bb-a228-9a87d065368f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4388</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4388']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afbbb5d0-125b-451a-bbb7-bb108894684f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4388</value>
      <webElementGuid>59816751-1923-4828-8bc9-0923b3e1c23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f366cb2-7f54-4798-a45e-655509e53ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4388&quot;)</value>
      <webElementGuid>47cb7741-2015-41e3-82ec-6a8e9bf57aa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4388']</value>
      <webElementGuid>6aa7be8c-c292-45d0-8546-40286ab6bee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>685992ab-53d9-4965-bd29-6e2369dddd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d0aa2258-0d21-4c7f-81f7-83dfe8291abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4388' and @type = 'text']</value>
      <webElementGuid>19f53e57-2677-4a1a-b8b7-41f0ab177f92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
