<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-4388</name>
   <tag></tag>
   <elementGuidId>ecdfc8b5-7f51-491a-85db-43dd5027b915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4388</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4388']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d177b4a-026c-4a02-9527-3af3d6e4a3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4388</value>
      <webElementGuid>fb3b6476-7b68-47ea-9194-fed4ac455139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4225a347-d956-40e8-a404-b36ccbf62f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4388&quot;)</value>
      <webElementGuid>483a166b-f091-4119-af58-cf61e9aa8d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4388']</value>
      <webElementGuid>ce12b3ab-492b-4021-a94a-b1a9b7ee26db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>6651ac02-92df-4255-ab08-f5aeab7f555c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dd3d02e8-17c8-40fc-bbf1-2253104112ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4388' and @type = 'text']</value>
      <webElementGuid>70580f0a-3fca-4606-9079-1bd7f461a953</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
