<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-4391</name>
   <tag></tag>
   <elementGuidId>dcb84b08-bcb7-4b62-84bf-558bddc8c72f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4391</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4391']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ece4882a-771b-43b7-87f2-c19bbe6ed84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4391</value>
      <webElementGuid>2433c9b0-0d8c-441a-9dd4-6441b15d6e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3cc14d8-094f-4dd5-8461-c516c1da5408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4391&quot;)</value>
      <webElementGuid>ad519f58-5dd6-4116-ad75-3503e12c09fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4391']</value>
      <webElementGuid>f2f6e7c9-642d-48cb-954a-4845391664e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>62511602-6073-43ab-aa3b-d90301f5835f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>d27f7219-da00-4c00-81d8-f03cf5192de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4391' and @type = 'text']</value>
      <webElementGuid>68dc416e-83a7-4833-ac5d-7455a24bef34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
