<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-4319</name>
   <tag></tag>
   <elementGuidId>c7861cad-1b1b-4927-af25-b6bd51fc0a1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4319</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4319']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>398bb1c2-3572-4047-92ca-1501bafe8a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4319</value>
      <webElementGuid>fceb8d9f-9aa8-4cb8-b6c5-9e202d24f210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd76b168-b676-4376-ba33-71ea5281088a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4319&quot;)</value>
      <webElementGuid>c4cd66a8-1a08-4250-a3b4-c7cd93fb7268</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4319']</value>
      <webElementGuid>c5b2ae2d-530b-4fe8-955d-40f48c38b677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>a6faa19f-3dd9-4474-b352-e9f02140eaf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>809bdc89-bb7f-4832-906c-81079bff29bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4319' and @type = 'text']</value>
      <webElementGuid>7cca8b96-5faa-4015-a214-7029bb60f0d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
