<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-4391</name>
   <tag></tag>
   <elementGuidId>2f28fc10-b533-4ffc-9472-f8f169ce8428</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4391</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4391']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42bd7ec9-a695-4bcf-876a-8a763444d01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4391</value>
      <webElementGuid>1daa190c-028a-44fe-86b6-359871f61ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0bdf9eec-7e96-4fcf-9d0d-58493ee53ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4391&quot;)</value>
      <webElementGuid>3470deeb-e355-4906-838a-248f79a2acfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4391']</value>
      <webElementGuid>7b08dea1-3150-4429-9f7d-19e116d46467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>a237ca76-a3f9-46b8-bd41-b3b0bc10bbcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>cca66f39-d5c2-4fc6-b3ad-ab5db39dfc40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4391' and @type = 'text']</value>
      <webElementGuid>1447a3f4-6c17-4103-b030-b177af15a905</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
