<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-4388</name>
   <tag></tag>
   <elementGuidId>d7ba7681-2a76-4293-b363-bf28a5879e23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4388</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4388']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0bbb835-ac25-4d64-a812-fe557518a8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4388</value>
      <webElementGuid>8729ec71-d9e6-4273-97fc-3a0e5aba54b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c73478b3-a9a0-4a5d-9fe9-137f80b1bd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4388&quot;)</value>
      <webElementGuid>fa29c1c2-1752-40d9-bfee-055d1cde1b16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4388']</value>
      <webElementGuid>3a71169a-7d6a-414b-9786-15b3b6850537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>44b06e19-a6c7-4eaa-85bc-994502a9d4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>77d8a77e-b252-4c68-92d5-9a5ea90d8d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4388' and @type = 'text']</value>
      <webElementGuid>52420a9b-0a89-4352-9f76-f017582e1968</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
