<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-4319</name>
   <tag></tag>
   <elementGuidId>aeba7360-9355-42b4-a465-1bdd9bc8f34a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4319</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4319']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98c12208-8ee7-42b8-9602-e02e47817289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4319</value>
      <webElementGuid>67f95bc0-985a-4a3b-ae23-894ca97105f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97c7add9-5374-48fe-9af3-10b39807bbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4319&quot;)</value>
      <webElementGuid>61f5c0d2-9704-4e04-8f2b-f221a774c02c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4319']</value>
      <webElementGuid>8b47a080-5095-4d23-a938-925027d9b73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>460ca10e-0078-46e7-8654-bd8c4c78029b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>17a469ec-1e6e-47c4-b0af-2f00ddde4d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4319' and @type = 'text']</value>
      <webElementGuid>9bd7d70d-795f-4061-b478-aea4d9df28d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
