<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-4322</name>
   <tag></tag>
   <elementGuidId>28371403-db91-4d24-9a20-2a41d9fc5be8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4322</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4322']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac584e67-75f9-430f-bfcf-8817e19985b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4322</value>
      <webElementGuid>ec35bd45-2f7d-4f79-ba9c-f44c9464ed45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fae4f9df-47d7-4f89-88e6-1fda058aebf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4322&quot;)</value>
      <webElementGuid>f30fefc7-d9a8-443b-a45b-dae0245e2ab2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4322']</value>
      <webElementGuid>e04280dc-eb3f-46bc-ab93-3b4f566c026a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>f4ddf5bf-cd07-44ea-9766-361f43f94047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>f4c4d579-c5f4-42c5-a5e6-439d2cd3bf98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4322' and @type = 'text']</value>
      <webElementGuid>a802eca1-6fe4-4f94-95b7-eb2e496c515b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
