<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-4322</name>
   <tag></tag>
   <elementGuidId>d3892de7-6df8-41e0-a548-4321c8820405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4322</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4322']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82dac1b3-b5f7-45cb-a6b4-0dcd1663a68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4322</value>
      <webElementGuid>451a40ad-6f56-4720-aa46-fb2ae2044977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00173627-1c6f-48b2-ac81-c16ccbab3ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4322&quot;)</value>
      <webElementGuid>a9ce52b5-89fb-4037-a6d7-a455372d7dca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4322']</value>
      <webElementGuid>1d508fb7-abb5-4b07-bb5f-bae1b2ba5672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>a5715273-357b-4119-9887-e8d190d90a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>526dbdb5-8f64-41f2-9e7f-46a5e9a29054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4322' and @type = 'text']</value>
      <webElementGuid>037bcb26-f00d-49dd-9eca-6faf8a7b7d23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
