<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-4319</name>
   <tag></tag>
   <elementGuidId>025d85c6-b4c3-46a6-9006-0192029b3637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4319</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4319']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>deadb4e0-0253-47d2-92f2-e2c568d3530b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4319</value>
      <webElementGuid>c2d55e5f-1d54-4de7-ab28-cefa7fb25beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9035951-ec99-4d84-a963-67b4c8a3d864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4319&quot;)</value>
      <webElementGuid>ac303cec-da24-48e7-8951-57c63bc3945b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4319']</value>
      <webElementGuid>f8d2de94-5f0d-4df9-89a7-2c79d410e1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>f078231f-706e-4724-b0a0-4f86baef497a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9b6969f5-cf0e-41ca-8bf0-09076845a0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4319' and @type = 'text']</value>
      <webElementGuid>be025d01-a569-4534-bace-e973f3d42961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
