<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Transaksi</name>
   <tag></tag>
   <elementGuidId>b53f3a4d-79fb-49ab-bd2a-0693977e1053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list-item-13168</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-13168']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f66d6ed-b129-43d5-99fe-8ac92f92d735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>45648464-aee5-47b1-8664-511786cfee6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>af20b0a1-55fa-438e-8501-f7758b3f587f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list-item-13168</value>
      <webElementGuid>4e0a45db-deb6-4cba-954e-a6c575fea634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item v-list-item--link theme--light</value>
      <webElementGuid>c1fbb832-9f69-4815-b3df-7b19e050ebba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Transaksi </value>
      <webElementGuid>b7fd003f-5049-43d4-97a7-b09a9247b941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-13168&quot;)</value>
      <webElementGuid>8b098c19-dbbe-4e55-adc8-ab63bcf8de64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='list-item-13168']</value>
      <webElementGuid>81099832-577a-4597-82af-63b7e3b4096e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div</value>
      <webElementGuid>9188b971-db9d-4d1e-889b-93cc7fbaf53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli'])[1442]/following::div[3]</value>
      <webElementGuid>de60049d-7b23-48cf-b06a-3b615fc01e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[1442]/following::div[3]</value>
      <webElementGuid>2544e102-9040-467d-9765-0a9884725997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::div[4]</value>
      <webElementGuid>fac13d23-ee8e-4e60-a143-eb1f297a98a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>a3f5f8e9-9c82-4190-a12f-fa29c9a6afb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'list-item-13168' and (text() = ' Transaksi ' or . = ' Transaksi ')]</value>
      <webElementGuid>b0e6ec52-ba23-40d0-82e3-53eb09162116</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
