<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-4403</name>
   <tag></tag>
   <elementGuidId>70ecf115-ba6c-49b0-bcd3-eb5f44a7b0f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4403</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4403']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04bc11c3-37a5-4e6d-9923-88e928451e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4403</value>
      <webElementGuid>f3e3eb86-493a-4ce8-8a1c-c053d4682160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c5906a2-0b62-420e-9e6e-093fc5968aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4403&quot;)</value>
      <webElementGuid>22c992c2-455a-4ef2-bc65-78017ee61a6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4403']</value>
      <webElementGuid>c77cf43d-ae29-40e9-83cd-efd80efaddf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>fbc8f268-3bfd-4449-82f8-66812ab4e507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7d8c3a3e-ce30-4b49-94b7-b1cf5b0cab27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4403' and @type = 'text']</value>
      <webElementGuid>014d3197-d56c-4c7a-b776-79caec4ead9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
