<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-4406</name>
   <tag></tag>
   <elementGuidId>df7613d3-7a21-4012-a8df-602cf1b6be1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4406</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4406']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b3babda-5dfc-427c-9754-fa180baea8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4406</value>
      <webElementGuid>2c7ebab9-3f6f-4f35-8d0e-535b5731305c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21512175-a3fe-4b90-b980-b82f5c8e0439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4406&quot;)</value>
      <webElementGuid>675fc52b-4d64-4d9a-a1df-f5c6536acba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4406']</value>
      <webElementGuid>950c4f8f-cc02-429a-98ec-09ab0c4ab09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>070ba814-86d4-4ac9-be79-1b3e5a4938f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>f0500d64-fb15-46dc-8520-79dc8c86faa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4406' and @type = 'text']</value>
      <webElementGuid>7f8b87fb-0f1a-4f77-be32-ae3affa63008</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
